INSERT INTO players (
    id, name, alliance_id, main_coordinates, notice,
    score_buildings, score_buildings_rank,
    score_research, score_research_rank,
    score_fleet, score_fleet_rank,
    score_defense, score_defense_rank,
    score_total, score_total_rank,
    combats_won, combats_draw, combats_lost, combats_total,
    honorpoints, honorpoints_rank,
    fights_honorable, fights_dishonorable, fights_neutral,
    destruction_units_killed, destruction_units_lost,
    destruction_recycled_metal, destruction_recycled_crystal,
    real_destruction_units_killed, real_destruction_units_lost,
    real_destruction_recycled_metal, real_destruction_recycled_crystal
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, 0), COALESCE(?, 0), COALESCE(?, 0), COALESCE(?, 0), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    alliance_id = excluded.alliance_id,
    main_coordinates = excluded.main_coordinates,
    notice = excluded.notice,
    score_buildings = excluded.score_buildings,
    score_buildings_rank = excluded.score_buildings_rank,
    score_research = excluded.score_research,
    score_research_rank = excluded.score_research_rank,
    score_fleet = excluded.score_fleet,
    score_fleet_rank = excluded.score_fleet_rank,
    score_defense = excluded.score_defense,
    score_defense_rank = excluded.score_defense_rank,
    score_total = excluded.score_total,
    score_total_rank = excluded.score_total_rank,
    combats_won = excluded.combats_won,
    combats_draw = excluded.combats_draw,
    combats_lost = excluded.combats_lost,
    combats_total = excluded.combats_total,
    honorpoints = excluded.honorpoints,
    honorpoints_rank = excluded.honorpoints_rank,
    fights_honorable = excluded.fights_honorable,
    fights_dishonorable = excluded.fights_dishonorable,
    fights_neutral = excluded.fights_neutral,
    destruction_units_killed = excluded.destruction_units_killed,
    destruction_units_lost = excluded.destruction_units_lost,
    destruction_recycled_metal = excluded.destruction_recycled_metal,
    destruction_recycled_crystal = excluded.destruction_recycled_crystal,
    real_destruction_units_killed = excluded.real_destruction_units_killed,
    real_destruction_units_lost = excluded.real_destruction_units_lost,
    real_destruction_recycled_metal = excluded.real_destruction_recycled_metal,
    real_destruction_recycled_crystal = excluded.real_destruction_recycled_crystal,
    updated_at = CURRENT_TIMESTAMP
